### ISSUE TITLE
DCA on count matrix: incompatibility with recent tensorflow and python versions

### ISSUE THREAD

**Issue by wenjiezeng08** [SDTC-CPMed/scDrugPrio#1]
Thanks for the package! I have a question about the DCA on the count matrix. I checked both the reference and the original DCA package tutorial, and it seems that the package has not been updated for a long time to keep up with the latest tensorflow version. 

It requires a tensorflow version >=2.0 but <2.5 to run DCA on the count matrix. However, the current tensorflow version compatible with the latest python version 3.12 is tensorflow 2.16, which is incompatible with DCA. 

I just wonder how did you solve this issue. Is there any alternatives?

Thanks!

**Comment by MartinSmel** [comment]
DCA is not part of scDrugPrio, see our publication: https://rdcu.be/dBWTN. 

We are aware that DCA has not been updated which might lead to problems. Though not tested, other denoising methods might work similarly well to DCA and one could therefore consider replacing DCA with another denoising method. One option could be to use scvi (https://docs.scvi-tools.org/en/stable/index.html), where function 'get_normalized_data', which can be used after training the model, should return analogical results to DCA. 

When we ran DCA we applied it to each data set through calling the python application from the terminal. In this setting we used python version 3.6 and tensorflow version 2.0.
